### ISSUE TITLE
plus_code field is not present in GeocoderResult interface

### ISSUE THREAD

**Issue by siegklenes** [googlemaps/js-types#16]
**Is your feature request related to a problem? Please describe.**
The result from geocode api returns plus_code field, but it was not declared in GeocoderResult interface

 **Describe the solution you'd like**
Include the plus_code field

 **Describe alternatives you've considered**
No alternatives

 **Additional context**
No additional context

**Comment by jpoehnelt** [comment]
I have a fix pending internally.

**Comment by jpoehnelt** [comment]
will be fixed in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53104
