### ISSUE TITLE
Missing `maneuver` property definition in `DirectionsStep` interface

### ISSUE THREAD

**Issue by dzonatan** [googlemaps/js-types#33]
The `maneuver` property is missing from the type definitions in this interface:

https://github.com/googlemaps/js-types/blob/09d392f4bd7e0a54ec5e9392d8a209ae4c816eaa/index.d.ts#L1602

Property legality:
https://developers.google.com/maps/documentation/directions/get-directions?hl=en#DirectionsStep

As a reference, the `@googlemaps/google-maps-services-js` has this properly already:
https://github.com/googlemaps/google-maps-services-js/blob/66720cb38652e42e31588a4132cdabf04b91355f/src/common.ts#L1082

**Comment by jpoehnelt** [comment]
Sorry I missed this. This was closed in https://github.com/googlemaps/js-types/commit/935f7fc7433bf76d94ce108a517762d13e18b8b6 and available in `@types/google.maps@3.47.3` (I think). Latest is `3.48.*`
